### ISSUE TITLE
Remove references to non-existent objects

### ISSUE THREAD

**Issue by thelastnode** [gt-webdev/attendance#142]
For example, users which are deleted being referenced by an org's attendance

**Comment by theJenix** [comment]
I think we need to be a bit careful with this one...if a user attended an event, we don't want to remove them from the attendance just because they deleted their account.  Instead I propose we make that account "archived"..it still shows up in attendance logs where they signed in, but they cannot log in/the account is otherwise inactive.  Otherwise, this presents a problem if we ever have to go back and verify attendance after the fact.

**Comment by thelastnode** [comment]
I agree

**Comment by thedekel** [comment]
the site isn't managing a massive amount of information per-user, and there's no way (that we know of) to see who is and isn't registered on the site, so deleting users is implemented in #169 as a way to remove test users and fake accounts.

closing this issue for the benefit of #170
